<?php

/**
 * ExpositoresTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExpositoresTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExpositoresTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Expositores');
    }
}