# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Coffee & Workshop - DIICC - UdeC
    description:  Workshop
    keywords:     Workshop, Informática, UdeC
    language:     es
    robots:       index, follow

  stylesheets:
    - main.css
    - parallax_slider.css
    - pirobox/style.css
    - intro_text.css
    - tiptip.css
    - Oswald.css
    - style1.css


  javascripts:
    - jquery-1.7.1.js
    - jquery.cslider.js
    - scripts.js
    - jquery_ui-1.8.9.min.js
    - pirobox_extended.js
    - jquery.galleryview.js
    - jquery.tabSlideOut.v1.3.js
    - jquery.lettering.js

  has_layout:     true
  layout:         layout
